### ISSUE TITLE
Entering decimal type in DT in is not working

### ISSUE THREAD

**Issue by Tatuk** [the-wrench-io/hdes#31]
Entering type refuses to accept . but allows user to use , which wrong (as a output) and as input entering 0.0 clears the input row

**Comment by admirkrilasevic** [comment]
Issue demo below - when entering a decimal number for the DECIMAL input type, typing a dot ('.') clears the input

https://user-images.githubusercontent.com/80248680/186674526-96e80cd7-2576-41b9-87c4-bdf784768c65.mp4

**Comment by admirkrilasevic** [comment]
Issue demo

https://user-images.githubusercontent.com/80248680/186677537-b24fee8f-f760-49fe-bcf4-58921b9aa461.mp4

**Comment by admirkrilasevic** [comment]
Fixed in hdes-composer release 0.2.48
