### ISSUE TITLE
Possibility to define value sets for From type of debug

### ISSUE THREAD

**Issue by Tatuk** [the-wrench-io/hdes#45]
For form based requires possibility to define values as list for string input type . This way the testing would be easier as many cases string are used to pass some params that affect the logic
<img width="1416" alt="Screenshot 2022-09-29 at 3 40 49" src="https://user-images.githubusercontent.com/24618519/192913281-20a7d0e6-661b-4e8e-99ba-e3b7d6b22b5c.png">

**Comment by admirkrilasevic** [comment]
Implemented in 3.130.54
